image: google/cloud-sdk:slim

variables:
  REGION: asia-southeast2
  REPO_NAME: gits-billing-fastapi
  IMAGE: $REGION-docker.pkg.dev/$GCP_PROJECT_ID/$REPO_NAME/$CLOUD_RUN_SERVICE_NAME:$CI_COMMIT_SHORT_SHA

stages:
  - deploy

before_script:
  - echo "$GCP_SERVICE_ACCOUNT_KEY" > gcp-key.json
  - gcloud auth activate-service-account --key-file gcp-key.json
  - gcloud config set project $GCP_PROJECT_ID
  - gcloud auth configure-docker $REGION-docker.pkg.dev

  - apt-get update && apt-get install -y docker.io
  - docker buildx create --use

deploy:
  stage: deploy
  tags:
    - gits-docker
  only:
    - main
  script:
    - docker buildx build --platform linux/amd64 -t $IMAGE --push .
    - gcloud run deploy $CLOUD_RUN_SERVICE_NAME \
      --image=$IMAGE \
      --platform=managed \
      --region=$REGION \
      --allow-unauthenticated \
      --port=8000
