image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ''

stages:
  - deploy

before_script:
  - apk add --no-cache python3 py3-pip
  - pip install --no-cache-dir gcloud
  - echo "$GCP_SERVICE_ACCOUNT_KEY" > gcp-key.json
  - curl https://sdk.cloud.google.com | bash
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud auth activate-service-account --key-file=gcp-key.json
  - gcloud config set project $GCP_PROJECT_ID
  - gcloud auth configure-docker

deploy:
  stage: deploy
  script:
    - docker build -t $IMAGE .
    - docker push $IMAGE
    - gcloud run deploy $CLOUD_RUN_SERVICE_NAME \
      --image $IMAGE \
      --region $GCP_REGION \
      --platform managed \
      --allow-unauthenticated
