image: google/cloud-sdk:slim

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ''
  REGION: asia-southeast2
  REPO_NAME: gits-billing-fastapi
  IMAGE: $REGION-docker.pkg.dev/$GCP_PROJECT_ID/$REPO_NAME/$CLOUD_RUN_SERVICE_NAME:$CI_COMMIT_SHORT_SHA

stages:
  - deploy

before_script:
  - echo "$GCP_SERVICE_ACCOUNT_KEY" > gcp-key.json
  - gcloud auth activate-service-account --key-file gcp-key.json
  - gcloud config set project $GCP_PROJECT_ID
  - gcloud auth configure-docker $REGION-docker.pkg.dev

deploy:
  stage: deploy
  tags:
    - gits-runner
  only:
    - main
  script:
    - |
      if ! gcloud artifacts repositories describe $REPO_NAME --location=$REGION > /dev/null 2>&1; then
        echo "Creating Artifact Registry $REPO_NAME"
        gcloud artifacts repositories create $REPO_NAME \
          --repository-format=docker \
          --location=$REGION \
          --description="Auto-created from GitLab CI"
      else
        echo "Artifact Registry $REPO_NAME already exists"
      fi
    - docker build -t $IMAGE .
    - docker push $IMAGE
    - |
      gcloud run deploy $CLOUD_RUN_SERVICE_NAME \
        --image=$IMAGE \
        --platform=managed \
        --region=$REGION \
        --allow-unauthenticated \
        --port=8000
