image: google/cloud-sdk:slim

variables:
  REGION: asia-southeast2
  REPO_NAME: gits-billing-fastapi
  IMAGE: $REGION-docker.pkg.dev/$GCP_PROJECT_ID/$REPO_NAME/$CLOUD_RUN_SERVICE_NAME:$CI_COMMIT_SHORT_SHA

stages:
  - deploy

before_script:
  - echo "$GCP_SERVICE_ACCOUNT_KEY" > gcp-key.json
  - gcloud auth activate-service-account --key-file gcp-key.json
  - gcloud config set project $GCP_PROJECT_ID
  - gcloud auth configure-docker $REGION-docker.pkg.dev

deploy:
  stage: deploy
  tags:
    - gits-shell
  only:
    - production
  script:
    - docker build -t $IMAGE .
    - docker push $IMAGE
    - |
      gcloud run deploy $CLOUD_RUN_SERVICE_NAME \
        --image=$IMAGE \
        --platform=managed \
        --region=$REGION \
        --allow-unauthenticated \
        --port=8000 \
        --set-env-vars "SUPABASE_URL=$SUPABASE_URL,SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY,SUPABASE_JWT_SECRET=$SUPABASE_JWT_SECRET,DATABASE_URI=$DATABASE_URI,CLIENT_URL=$CLIENT_URL,INTERNAL_API_KEY=$INTERNAL_API_KEY" \
        --min-instances=1 \
        --max-instances=10
