image: google/cloud-sdk:slim

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ''

stages:
  - deploy

before_script:
  - echo "$GCP_SERVICE_ACCOUNT_KEY" > gcp-key.json
  - gcloud auth activate-service-account --key-file=gcp-key.json
  - gcloud config set project $GCP_PROJECT_ID
  - gcloud auth configure-docker

deploy:
  stage: deploy
  script:
    - docker build -t gcr.io/$GCP_PROJECT_ID/$CLOUD_RUN_SERVICE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker push gcr.io/$GCP_PROJECT_ID/$CLOUD_RUN_SERVICE_NAME:$CI_COMMIT_SHORT_SHA
    - gcloud run deploy $CLOUD_RUN_SERVICE_NAME \
      --image gcr.io/$GCP_PROJECT_ID/$CLOUD_RUN_SERVICE_NAME:$CI_COMMIT_SHORT_SHA \
      --platform managed \
      --region $GCP_REGION \
      --allow-unauthenticated
