image: google/cloud-sdk:latest

services:
  - name: docker:dind
    variables:
      DOCKER_TLS_CERTDIR: ''

stages:
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ''
  IMAGE: gcr.io/$GCP_PROJECT_ID/$CLOUD_RUN_SERVICE_NAME:$CI_COMMIT_SHORT_SHA

before_script:
  - echo "$GCP_SERVICE_ACCOUNT_KEY" > gcp-key.json
  - gcloud auth activate-service-account --key-file gcp-key.json
  - gcloud config set project $GCP_PROJECT_ID
  - gcloud auth configure-docker

deploy:
  stage: deploy
  script:
    - docker build -t $IMAGE .
    - docker push $IMAGE
    - gcloud run deploy $CLOUD_RUN_SERVICE_NAME \
      --image $IMAGE \
      --region $GCP_REGION \
      --platform managed \
      --allow-unauthenticated
