image: google/cloud-sdk:slim

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ''
  REGION: us-central1
  GCP_PROJECT_ID: gits-gcp-billing
  ARTIFACT_REPO: gits-billing-fastapi
  SERVICE_NAME: gits-billing-api
  IMAGE: us-central1-docker.pkg.dev/$GCP_PROJECT_ID/$ARTIFACT_REPO/$SERVICE_NAME:$CI_COMMIT_SHORT_SHA

stages:
  - deploy

before_script:
  - echo "$GCP_SERVICE_ACCOUNT_KEY" > gcp-key.json
  - gcloud auth activate-service-account --key-file gcp-key.json
  - gcloud config set project $GCP_PROJECT_ID
  - gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

deploy_to_cloud_run:
  stage: deploy
  script:
    - docker build -t $IMAGE -t us-central1-docker.pkg.dev/$GCP_PROJECT_ID/$ARTIFACT_REPO/$SERVICE_NAME:latest .

    - docker push $IMAGE
    - docker push us-central1-docker.pkg.dev/$GCP_PROJECT_ID/$ARTIFACT_REPO/$SERVICE_NAME:latest

    - gcloud run deploy $SERVICE_NAME \
      --image us-central1-docker.pkg.dev/$GCP_PROJECT_ID/$ARTIFACT_REPO/$SERVICE_NAME:latest \
      --platform managed \
      --region $REGION \
      --allow-unauthenticated
